### ISSUE TITLE
mask_matching_filtering_threshold not set in cellpose segmentation

### ISSUE THREAD

**Issue by Swarchal** [MannLabs/scPortrait#114]
Hi,

Within the legacy branch, in the config.yml if the CytosolSegmentationCellpose section is missing a `match_masks` or `filtering_threshold_mask_matching` value, match_masks now defaults to True, but a value for `self.mask_matching_filtering_threshold` is never set.

https://github.com/MannLabs/scPortrait/blob/fc6f25b8ec8cff73e1bf4acc8512e84927707451/src/scportrait/pipeline/workflows.py#L530-L547

This later causes an AttributeError here:

https://github.com/MannLabs/scPortrait/blob/fc6f25b8ec8cff73e1bf4acc8512e84927707451/src/scportrait/pipeline/workflows.py#L1522-L1528

```python-traceback
[21/11/2024 01:52:58] Segmenting nucleus using the following model: nuclei                                                    
[21/11/2024 13:30:44] Segmenting cytosol using the following model: cyto2                                                     
Traceback (most recent call last):                                                                                            
  File "/nemo/stp/hts/working/scott/projects/20240918_dan_tedescoLab_slides/project.py", line 39, in <module>                 
    project.segment()                                                                                                         
  File "/nemo/stp/hts/working/scott/code/scPortrait/src/scportrait/pipeline/project.py", line 752, in segment                 
    self.segmentation_f(self.input_image, *args, **kwargs)                                                                    
  File "/nemo/stp/hts/working/scott/code/scPortrait/src/scportrait/pipeline/base.py", line 204, in __call__                   
    if callable(process):                                                                                                     
  File "/nemo/stp/hts/working/scott/code/scPortrait/src/scportrait/pipeline/workflows.py", line 1579, in process              
    self.cellpose_segmentation(input_image)                                                                                   
  File "/nemo/stp/hts/working/scott/code/scPortrait/src/scportrait/pipeline/workflows.py", line 1525, in cellpose_segmentation
    filtering_threshold=self.mask_matching_filtering_threshold,                                                               
AttributeError: 'CytosolSegmentationCellpose' object has no attribute 'mask_matching_filtering_threshold'                     
```

If you like I could submit a pull request where `_check_for_mask_matching_filtering()` also sets a default parameter for `mask_matching_filtering_threshold` if `match_masks` isn't present in the config?

**Comment by sophiamaedler** [comment]
Thanks for catching this. A PR would be amazing :-)

**Comment by Swarchal** [comment]
https://github.com/MannLabs/scPortrait/pull/115
